        <!-- <form class="contact custom" 
         action="<?php echo $this->getUrl('product/product/product');?>"
         id="custom-form"
         method="post">
         <div>
            <input
                type="text"
                name="remarks"
                id="remarks"
                maxlength="100"/><br><br>
             </div>
             <style>
                   /* #heading{
                       color:red;
                    } */
                </style>
             <h5 id="heading">testing</h5>
            <div class="primary">
           
                <button type="submit" title="<?php  echo __('Save') ?>" class="action submit primary" id="custom_btn">
                    <span><?php  echo __('Save') ?></span>
                </button>
            </div>
        </form> -->